[pytest]
addopts = --cov=hnn_core --cov-report=term-missing
testpaths = hnn_core/tests
markers =
    uses_mpi: tests which should NOT be run in an embarrassingly-parallel fashion
    incremental: run tests with prerequisites in incremental order

